KAFKA_TRUSTSTORE_BASE64: ${KAFKA_TRUSTSTORE_BASE64}
KAFKA_KEYSTORE_BASE64: ${KAFKA_KEYSTORE_BASE64}
spring:
  kafka:
    bootstrap-servers: ${AIVEN_HOST}

    properties:
      security.protocol: SSL
      ssl.truststore.location: file:/tmp/client.truststore.jks
      ssl.truststore.password: changeit
      ssl.truststore.type: PKCS12
      ssl.keystore.location: file:/tmp/client.keystore.jks
      ssl.keystore.password: changeit
      ssl.keystore.type: PKCS12
      ssl.key.password: changeit

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
      url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
      username: ${PGUSER}
      password: ${PGPASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${EXPIRATION_TOKEN}